logging:
  level:
    ROOT: INFO
    org.springframework: ALL
    org.hibernate: ERROR
    com.example.demo.controller: ALL
  
  pattern:
    console: "- %msg%n"
    file: "*[%-5p]-- %m--%n"
  file: logs/demo.log
server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:file:~/demo
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /db
  jpa:
    hibernate:
      ddl-auto: create-drop  